/*
 * This file is part of the Bastille library.
 *
 * For licensing information please see the file license.txt included in the release.
 * A copy of this licence can also be found at
 *   http://www.opensource.org/licenses/artistic-license-2.0.php
 */
package org.weborganic.bastille.log.logback;

import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import org.slf4j.LoggerFactory;
import org.weborganic.bastille.log.LogInfo;
import org.weborganic.bastille.log.UnexpectedFrameworkException;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.TurboFilterList;
import ch.qos.logback.core.Appender;
import ch.qos.logback.core.FileAppender;

import com.topologi.diffx.xml.XMLWritable;

/**
 * A implementation of the log info interface for the Logback framework.
 *
 * @author Christophe Lauret
 * @version Bastille 0.8.5 - 5 February 2013
 */
public final class LogbackInfo implements LogInfo {

  /**
   * Sets up the recent events turbo filter.
   */
  @Override
  public void init() {
    LoggerContext context = (LoggerContext)LoggerFactory.getILoggerFactory();
    // Ensure that it's not already there
    TurboFilterList list = context.getTurboFilterList();
    list.addIfAbsent(RecentEventsFilter.singleton());
  }

  @Override
  public boolean supportsListLogDirectories() {
    return true;
  }

  /**
   * Returns the list of log directories.
   *
   * @return the list of log files generated by Logback
   */
  @Override
  public List<File> listLogDirectories() {
    List<File> files = new ArrayList<File>();
    try {
      LoggerContext context = (LoggerContext)LoggerFactory.getILoggerFactory();
      Set<FileAppender<ILoggingEvent>> fileappenders = getFileAppenders(context);
      for (Iterator<FileAppender<ILoggingEvent>> i = fileappenders.iterator(); i.hasNext();) {
        FileAppender<ILoggingEvent> appender = i.next();
        String pattern = appender.getFile();
        File f = new File(pattern);
        files.add(f.getParentFile());
      }

    } catch (ClassCastException ex) {
      throw new UnexpectedFrameworkException("Expected LogBack", ex);
    }
    return files;
  }

  /**
   * @return always <code>true</code>.
   */
  @Override
  public boolean supportsRecentEvents() {
    return true;
  }

  @Override
  public List<? extends XMLWritable> listRecentEvents() {
    return RecentEventsFilter.getCopyOfEvents();
  }

  // private helpers
  // ----------------------------------------------------------------------------------------------

  private static Set<FileAppender<ILoggingEvent>> getFileAppenders(LoggerContext context) {
    Set<FileAppender<ILoggingEvent>> fileappenders = new HashSet<FileAppender<ILoggingEvent>>();
    List<Logger> loggers = context.getLoggerList();
    for (Logger logger : loggers) {
      for (Iterator<Appender<ILoggingEvent>> i = logger.iteratorForAppenders(); i.hasNext();) {
        Appender<ILoggingEvent> appender = i.next();
        if (appender instanceof FileAppender) {
          fileappenders.add((FileAppender<ILoggingEvent>)appender);
        }
      }
    }
    return fileappenders;
  }

  /**
   * Returns the list of all appenders used in Logback.
   *
   * @param context The logger context.
   *
   * @return The list of appenders in use.
   */
  private static Set<Appender<ILoggingEvent>> getAppenders(LoggerContext context) {
    Set<Appender<ILoggingEvent>> appenders = new HashSet<Appender<ILoggingEvent>>();
    List<Logger> loggers = context.getLoggerList();
    for (Logger logger : loggers) {
      for (Iterator<Appender<ILoggingEvent>> i = logger.iteratorForAppenders(); i.hasNext();) {
        Appender<ILoggingEvent> appender = i.next();
        appenders.add(appender);
      }
    }
    return appenders;
  }

}
